### ISSUE TITLE
Sidekiq 3.2

### ISSUE THREAD

**Issue by sahin** [russ/sidekiq-history#1]
This is a great gem, it is very needed. 

Do u have plans to update it for sidekiq 3.2?

**Comment by russ** [comment]
Thank you. I do but haven't had the need to yet. Have you looked into what it might take?

**Comment by sahin** [comment]
I can, there are some small changes and better ways to catch the jobs. I will check more deeply. 

Btw, I will add this gem in the https://github.com/mperham/sidekiq/wiki/Related-Projects

**Comment by russ** [comment]
Btw. I've made this work with 3.3.0.
