### ISSUE TITLE
Order by started desc

### ISSUE THREAD

**Issue by fmluizao** [russ/sidekiq-history#10]
Hi,

I'm seeing the jobs sorted the oldest to the newest... I think it would be more useful to see the completed jobs the newest to the oldest. 

It's possible to do that?

Thanks

**Comment by russ** [comment]
I've recently been thinking the same thing. Guess I just needed a push. I've updated the gem to version 0.0.7. That should do the trick. Thanks!

**Comment by fmluizao** [comment]
Thanks for the quick response!
