### ISSUE TITLE
Modify history information

### ISSUE THREAD

**Issue by ArgirisKatsoulieris** [russ/sidekiq-history#21]
Thanks for this useful gem!

Is it possible to filter information shown in history?
I use devise and rails log filters the emails but they are shown as plaintext in sidekiq history.

thanks in advance

**Comment by russ** [comment]
There currently is no way to do that. Shouldn't be too much work to figure it out. Though, I'm looking for maintainers on this project. I haven't touched this code in forever and don't use Ruby much anymore.
