### ISSUE TITLE
Support for Sidekiq 6.5

### ISSUE THREAD

**Issue by jcsrb** [russ/sidekiq-history#22]
Sidekiq changed a lot of the internals for version 6.5 in preparation for version 7
https://github.com/mperham/sidekiq/blob/main/Changes.md#650

which include the removal of `Sidekiq::Util`  

a quick look at https://github.com/russ/sidekiq-history/blob/master/lib/sidekiq/history/middleware.rb I can see only the `identity`  method used from sidekiq util, but there could be more

**Comment by BurningMoneySlowly** [comment]
Any updates with this?

**Comment by russ** [comment]
No. I'm looking for a new maintainer on this project.

**Comment by joshRpowell** [comment]
Some discussion here https://github.com/mperham/sidekiq/discussions/5389 opened up a PR for collaboration #23 

`identity` method used [here](https://github.com/mperham/sidekiq/blob/90650169ecd2a54f69282e4f663e6821a0139220/lib/sidekiq/component.rb#L41)
