### ISSUE TITLE
Write usage instructions

### ISSUE THREAD

**Issue by tylercollier** [russ/sidekiq-history#3]
You wrote

> TODO: Write usage instructions here

It's time :-)

Consider my case: I think I want to use this gem because I'm having trouble with sidekiq, and so think seeing the history will help. I'm already frustrated with sidekiq and scrambling to find out what's happening to my jobs, so I don't want to go read gem source.

You went to the trouble of creating the gem, why not write it up?

:+1:

**Comment by jwoertink** [comment]
@tylercollier I don't think there would be much to write up. After you install the gem, you're done. I haven't needed to configure anything to make it work. Are you running into an issue using it?

**Comment by tylercollier** [comment]
From the readme:

> A really simple addition to sidekiq web to enable a job history log

Where is the log? In a file? Or is it shown on the sidekiq admin website?

**Comment by jwoertink** [comment]
It's mounted into the sidekiq web admin. It just adds a new `History` tab.

**Comment by russ** [comment]
Hey @tylercollier thanks for the question. It's really simple. You just add the gem to your Gemfile and reboot your app. There will be a new History tab in the web interface of sidekiq.

As far as debugging what is going on in sidekiq I'm not sure this will totally help. This is more of a reference for what is going on in production without having to grep a log file. This will show you what jobs ran and when. If you are having problems with your jobs I recommend digging into the sidekiq log file. That will give you the most helpful information.

**Comment by tylercollier** [comment]
Thank you both. I could have figured this out for myself. But it wasn't merely laziness on my part. I figured you took the time to write the gem, so I assume you want others to use it. You'll get more people to use it if you explain what it is / how it works (which you have now done with the readme update). The screenshot is perfect.

**Comment by russ** [comment]
I forgot to mention that I added a screenshot of the plugin to the README.
